"""empty message

Revision ID: 8e8d8af6f215
Revises: b3b564bc1a05
Create Date: 2020-12-23 10:04:24.056195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8d8af6f215'
down_revision = 'b3b564bc1a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orders', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('order', 'orders')
    # ### end Alembic commands ###
